/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;
import java.sql.*;
import java.text.*;
import java.text.SimpleDateFormat;
import java.awt.print.*;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

import javafx.scene.web.WebView;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JTextField;
/**
 *
 * @author saquib
 */
public class CreateBill extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateBill
     */
    public CreateBill() {
        initComponents(); 
        Fillcombo();
        showdate();
        getsum();
        billno();
        AutoCompleteDecorator.decorate(jComboBox2);
        this.setLocation(260, 10);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setEditable(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setEditable(false);
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField8.setEnabled(false);
        jTextField8.setEditable(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 =  new javax.swing.JLabel(); 

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("New Bill");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel1.setText("Bill No");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel2.setText("Product ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel3.setText("Name");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); 

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel4.setText("MRP");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); 

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel5.setText("Quantity");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); 

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel6.setText("Discount");
        
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("Customer Address");
        
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); 

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFrames/7-32.png"))); 
        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\saquib\\Desktop\\DeleteRed.png")); 
        jButton2.setText("Remove");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jTextField7.setHighlighter(null);
        jTextField7.setMargin(new java.awt.Insets(2, 4, 2, 2));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyFrames/print.png"))); 
        jButton4.setText("Print");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel9.setText("Date");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); 

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantity", "Name", "Mrp", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); 
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); 
        jLabel8.setText("Customer Name");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14));
        
        JLabel jLabel11 = new JLabel("Customer Address");
        jLabel11.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        textField = new JTextField();
        
        jLabel12 = new JLabel("Customer Phone #");
        jLabel12.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        textField_1 = new JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(701, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addGap(0, 22, Short.MAX_VALUE)
        										.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(jLabel11)
        										.addPreferredGap(ComponentPlacement.RELATED))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(jLabel8)
        										.addPreferredGap(ComponentPlacement.RELATED))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        										.addPreferredGap(ComponentPlacement.RELATED))
        									.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
        										.addPreferredGap(ComponentPlacement.RELATED))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        										.addPreferredGap(ComponentPlacement.RELATED)))
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        											.addGroup(jPanel1Layout.createSequentialGroup()
        												.addGap(26)
        												.addComponent(jButton2))
        											.addGroup(jPanel1Layout.createSequentialGroup()
        												.addPreferredGap(ComponentPlacement.RELATED)
        												.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        													.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        													.addComponent(textField_1, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        													.addComponent(jTextField2, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        													.addComponent(textField, 149, 149, Short.MAX_VALUE))))
        										.addGap(86))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addPreferredGap(ComponentPlacement.RELATED)
        										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        											.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        											.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        											.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        											.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        											.addComponent(jComboBox2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE))
        										.addGap(87))))
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED)))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel12)
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
        							.addGap(119))
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addGap(18)
        									.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE)
        									.addGap(72))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE)
        									.addGap(30))))))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(22)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel1))
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel9)))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 339, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        					.addGap(16)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel12)
        						.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(20)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        					.addGap(16)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel3)
        						.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(16)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(20)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(35)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jButton1)
        						.addComponent(jButton2))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel7))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 577, Short.MAX_VALUE)
        			.addGap(63))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
     String tmp=(String)jComboBox2.getSelectedItem();
     String sql1="SELECT * FROM `stock` WHERE `id`=?";
     Connection con;
   PreparedStatement pst;
   ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/qb", "root", "passcode");
            pst=con.prepareStatement(sql1);  
            pst.setString(1, tmp);
            rs1=pst.executeQuery();
            if(rs1.next())
            {
                String add=rs1.getString("pname");
                jTextField3.setText(add);
                String add1=rs1.getString("mrp");
                jTextField4.setText(add1);
            }
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible
    
 // bill no
 public void billno()
 {
     String sql1="SELECT COUNT(*) FROM `bill`";
     Connection con;
   PreparedStatement pst;
   ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/qb", "root", "passcode");
            pst=con.prepareStatement(sql1);  
            //pst.setInt(1, 20);
            rs1=pst.executeQuery();
            while(rs1.next())
            {
                //String add3=rs1.getString("pname");
                int g=Integer.parseInt(rs1.getString(1));
                g=g+1;
                jTextField1.setText(String.valueOf(g));
                //String add1=rs1.getString("mrp");
                //jTextField4.setText(add1);
            }
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
 }
    //insert data into billtable
    public void billupdate()
    {
    	System.out.println(jTextField1.getText()+",'"+jTextField2.getText()+"',"+jTextField2.getText()+"',"+jTextField7.getText()+",'"+jTextField8.getText()+"'");
   String query="INSERT INTO `bill`(bno,`cname`,`caddress`,cphone,pid,`pname`,qty,amt,`pdate`) VALUES("+jTextField1.getText()+",'"+jTextField2.getText()+"',"+jTextField2.getText()+"',"+jTextField7.getText()+",'"+jTextField8.getText()+"');";
    
       Connection con;    
       Statement st;
       try{
            con = con=DriverManager.getConnection("jdbc:mysql://localhost/qb", "root", "passcode");
           st = con.createStatement();
           st.executeUpdate(query);
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null ,e);
       }
           }


//Sum of jtable
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
    
                 String s2= jTextField5.getText();//quantity
                 String s1=jTextField4.getText(); //mrp
                 String s3=jTextField6.getText();
                 int d=0;
                 System.out.println("Saquib"+s3+"Iqubal");
                 if(!s3.equalsIgnoreCase("")) {
                 d=Integer.parseInt(s3);
                 }
                 int a=Integer.parseInt(s1);
                 int b;
                  b = Integer.parseInt(s2); 
                 int c = a * b;
                 int e = c -((d*c)/100);
                 
                 String result=String.valueOf(e);
                 
                 
                 model.addRow(new Object[]{jTextField5.getText(),jTextField3.getText(),jTextField4.getText(),result});
                 getsum();
                 
                 // Update query;
                 String sql1="UPDATE `stock` SET `available`=`available` - '"+jTextField5.getText()+"' WHERE `id`='"+String.valueOf(jComboBox2.getSelectedItem())+"'";
     Connection con;
   Statement st;
  // ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/qb", "root", "passcode");
            st=con.createStatement();  
            //st.setString(1, tmp);
            st.executeUpdate(sql1);
            
     }
     catch(Exception ex)
     {
         JOptionPane.showMessageDialog(null,ex);
     }
    }//GEN-LAST:event_jButton1ActionPerformed
      public void getsum()
      {
          int sum=0;
          for(int i=0; i<jTable1.getRowCount(); i++)
          {
              sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
          }
          jTextField7.setText(Integer.toString(sum));
      }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
            model.removeRow(jTable1.getSelectedRow());
            // Update query;
                 String sql1="UPDATE `stock` SET `available`=`available` + '"+jTextField5.getText()+"' WHERE `pname`='"+jTextField3.getText()+"'";
     Connection con;
   Statement st;
  // ResultSet rs1;
     try{
         con=DriverManager.getConnection("jdbc:mysql://localhost/qb", "root", "passcode");
            st=con.createStatement();  
            //st.setString(1, tmp);
            st.executeUpdate(sql1);
            
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        billupdate();
        
        try{
            invoice_job();
        }
        catch(Exception e)
        {
            System.err.format("Cannot print %%n",e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
      jTextField5.setText(model.getValueAt( jTable1.getSelectedRow(), 0).toString());
      jTextField4.setText(model.getValueAt( jTable1.getSelectedRow(), 2).toString());
      jTextField3.setText(model.getValueAt( jTable1.getSelectedRow(), 1).toString());
    	invoice_job();
    }//GEN-LAST:event_jTable1MouseClicked
    public static  String DateFormat = "yyyy-MM-dd";
    public void showdate()
    {
      Calendar cal= Calendar.getInstance();
      SimpleDateFormat format = new SimpleDateFormat(DateFormat);
      jTextField8.setText(format.format(cal.getTime()));

        
    }
    private void Fillcombo()
    {
        String sql;
        sql = "SELECT * FROM `stock`";
    Connection con;
   PreparedStatement ps;
   ResultSet rs;
        try
        {
          con=DriverManager.getConnection("jdbc:mysql://localhost/qb", "root", "passcode");
            ps=con.prepareStatement(sql);  
            rs=ps.executeQuery();
            while(rs.next())
            {
                String id=rs.getString("id");
                jComboBox2.addItem(id);
            }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);    
        }
        
    }
    
    public void invoice_job()   
    {

     try 
     {
       int rows=jTable1.getRowCount();
       String head = String.format("%50s\n\n", "   Invoice Reciept   ");
       String company = String.format("%50s\n\n", "<b>My Comapnany</b>");
       String s = String.format("%-15s %15s %20s %20s\n", "Item",        "Qty",        "MRP",        "Price");
       String s1 = "---------------------|---------------------|---------------------|---------------------|\n---------------------|---------------------|---------------------|---------------------|\n";    
       String output =company+ head + s + s1;
       System.out.println(output);
       for(int row = 0; row<rows; row++)

       {   

          String Names = (String)jTable1.getValueAt(row, 1);
          String Quanti = (String)jTable1.getValueAt(row, 0);
          String Price = (String)jTable1.getValueAt(row, 3);
          String MRP = (String)jTable1.getValueAt(row, 2);
          System.out.println(Names+" |"+Quanti+" | "+Price+" | "+MRP);
          
          String line = String.format("%-15s %15s %20s %20s\n",Names,Quanti,MRP,Price);  
          output += line;
          String lin2 = "---------------------|---------------------|---------------------|---------------------|\n";
          output += lin2;



        }

        String Total = String.format("%37s\n","Total");
       // String total = String.format("%37s\n\n",lbl.getText()); 
        String footer = String.format("%-15s\n", "Powered By Web Instance  | www.webinstance.in");
        //output += Total + total + footer;
        textPane.setContentType("text/html");
        textPane.setText(output);

        JOptionPane.showMessageDialog(null, output);


        PrinterJob printerJob = PrinterJob.getPrinterJob();
        PageFormat pageFormat = printerJob.defaultPage();
        Paper paper = new Paper();
        paper.setSize(500.0, (double) (paper.getHeight() + rows * 10.0));
        paper.setImageableArea(rows, rows, paper.getWidth() - rows * 2, paper.getHeight() - rows * 2);
        pageFormat.setPaper(paper);
        pageFormat.setOrientation(PageFormat.PORTRAIT);
        printerJob.setPrintable(textPane.getPrintable(null, null), pageFormat);
        printerJob.print();

     } 
     catch ( Exception e ) 
     {

         e.printStackTrace();
     }
 }
    
    
   /* 
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private JTextPane textPane = new JTextPane();
    private JTextField textField;
    private JLabel jLabel12;
    private JTextField textField_1;
}
